nginx:
 image: aciden/repo:nginx
 ports:
  - 8080:80 # Проброс портов для внешнего доступа
 volumes:
  - ./logs:/etc/logs/nginx
 volumes_from:
  - fpm:rw
 environment:
  - NGINX_HOST=localhost
  - NGINX_PORT=80
 command: nginx -g "daemon off;"
 links:
  - fpm
fpm:
 image: aciden/repo:php7.0-fpm
 volumes:
  - ./api:/var/www/html:rw
links:
  - postgres
postgres:
 image: postgres:latest
 ports:
  - 5434:5432 # Проброс портов для внешнего доступа
 environment:
  POSTGRES_PASSWORD: <myPassword>
  POSTGRES_USER: postgres
  PGDATA : /data/postgres