nginx:
 image: nginx:1.12-alpine
 ports:
  - 8080:80
 volumes:
  - ./logs:/var/logs/nginx
  - ./contaners/nginx/conf:/etc/nginx/conf.d
 volumes_from:
  - fpm:rw
 links:
  - fpm
fpm:
 image: phalconphp/php-fpm:7
 volumes:
  - ./api:/var/www/html:rw
 environment:
  - PHP_MEMORY_LIMIT=512M
  - MAX_UPLOAD=50M
  - PHP_MAX_POST=100M
 links:
  - postgres
postgres:
 image: postgres:10.0-alpine
 expose:
  - 5432
 ports:
  - 5435:5432
 volumes:
  - ./database/postgres:/var/lib/postgresql/data
 environment:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 12345
  POSTGRES_DB: native