nginx:
 image: aciden/nginx-1.12
 ports:
  - 8080:80
 volumes:
  - ./logs:/var/logs/nginx
  - ./contaners/nginx/conf:/etc/nginx/conf.d
 volumes_from:
  - fpm:rw
 command: nginx -g "daemon off;"
 links:
  - fpm
fpm:
 image: aciden/php7.0-fpm
 volumes:
  - ./api/public:/var/www/html:rw
 environment:
  - PHP_MEMORY_LIMIT=512M
  - MAX_UPLOAD=50M
  - PHP_MAX_POST=100M
postgres:
 image: aciden/postgres-10.0
 ports:
  - 5435:5432
 environment:
  POSTGRES_PASSWORD: 12345
  POSTGRES_USER: postgres
